name: Build e deploy para o Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurando a versão do .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build e Publish
        run: |
          dotnet build
          dotnet publish src/HealthMed.Api/HealthMed.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Iniciando container SQL Server para testes integrados
        run: docker-compose -f "docker-compose.yml" up -d --build
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download do artefato para o build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.DataBase: ${{ secrets.CONNECTIONSTRING }}
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'healthmedfiap'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_52f617011a8a4e288cde69f59cfff749 }}
          package: .
